import { Roboto_Mono } from 'next/font/google'
import './styles/globals.scss'

const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={robotoMono.className}>{children}</body>
		</html>
	)
}
