import { Roboto_Mono } from 'next/font/google'
import '../styles/globals.scss'
import Footer from '../_components/Footer'
import Header from '../_components/Header'
import Menu from '../_components/Menu'
import Providers from '../providers'

const robotoMono = Roboto_Mono({ subsets: ['latin'] })

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }

export default function RootLayout({
	children,
	params: { locale }
	
}) {
	
	return (
		<html lang='en'>
			<body className={robotoMono.className}>
				<Providers>
					<div className='wrapper'>
						<Header locale={locale} />
						<Menu locale={locale} style={{border: '1px solid gold'}}/>
						{children}
						<Footer locale={locale} />
					</div>
				</Providers>
			</body>
		</html>
	)
}
